version: '3.8'

services:
  dair:
    image: dair_web:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sql1
      - mongodb 
    ports:
      - "8080:80"

  sql1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "BadMand120@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
